### ISSUE TITLE
sync_pgviews should catch the syncdb signal and run itself

### ISSUE THREAD

**Issue by adamhaney** [zacharyvoase/django-postgres#5]
I'm running into a problem where the test runner is unaware of views that I've created, which is causing model validation issues and missing views that I can't write tests against. It seems the easiest way to fix this problem would be to have sync_pgviews catch syncdb and run itself in the least forceful way possible. I'd be more than happy to implement this if this seems like a good idea. My next try would be to implement a subclasses test runner (like south does). Any ideas?

**Comment by scott-w** [comment]
This conflicts with #3 which was implemented - essentially it conflicts with migrations.

I worked around this issue by extending TestCase.setUp() like so:

```
def setUp(self):
    call_command('sync_pgviews', *[], **{})
    # My other setup stuff here
```

Regards,
Scott

**Comment by zacharyvoase** [comment]
So, catching the syncdb signal is what we used to do originally. However in order to be more compatible with migrations we switched to the separate `sync_pgviews`. So yeah, calling the command from `setUp()` is the best option for now. Don’t forget to call the supermethod if you’re using the South test runner.
